### ISSUE TITLE
Personne non affichée ?

### ISSUE THREAD

**Issue by bastianfbr** [anisayari/createurstech.fr#106]
Dans le json il y a des personnes (pour l'instant j'en ai vu qu'une mais c'est peut-être le cas pour d'autres) qui ne sont pas affichées et qu'on ne peut rechercher.

Exemple :
  "ITers": {
    "youtube_channel_id": "UCHSJJ_tLIvi9w67LM0hzxkA",
    "youtube_channel_username": "ITers",
    "categories": "dev_web actu_tech",
    "twitch_channel_name": "iter_fr",
    "twitter_screen_name": "ITer_fr"
  },

ITers n'est pas recherchable
![image](https://user-images.githubusercontent.com/29505634/125195057-448aa800-e254-11eb-8659-545e7ab1a770.png)

**Comment by anisayari** [comment]
C'est normal il y a une vérification automatique des critères.  Il faut avoir **au moins 10k abonnés** sur Youtube pour être référencé.

Donc on peut être dans le json mais non affichés sur le site. Tous les jours le script qui récupère les données vérifie les critères. Et si les check sont passés il affiche le profil sur le site.
