### ISSUE TITLE
Les cartes non centrées.

### ISSUE THREAD

**Issue by DimitriTimoz** [anisayari/createurstech.fr#24]
### Les cartes ne sont pas centrés par rapport à la page:

![Capture d’écran 2021-07-03 à 02 42 47](https://user-images.githubusercontent.com/45998396/124338451-5c08c780-dba8-11eb-9076-298a8e936873.png)

**Comment by anisayari** [comment]
résolu avec e21809ed1c7123a6d500ea11045b19d68e8daa24
