### ISSUE TITLE
Filtre on fonctionnel 

### ISSUE THREAD

**Issue by Gr0bs** [anisayari/createurstech.fr#28]
Les filtres ne fonctionne pas, que ce soit un sujet avec déjà des personnes présentes ou bien juste une plateforme. 
Même en voulant revenir sur **tout** ca n'affiche plus ce qu'on peut voir au départ. 

Désolé si c'est encore qu'une feature et pas implenté. :) 

![Screenshot 2021-07-03 at 14-07-58 Les createurs Tech français](https://user-images.githubusercontent.com/62292954/124353673-285d8a00-dc08-11eb-9f1d-ebf5905d8ee5.png)

**Comment by anisayari** [comment]
Oui les filtres "sujet" ne fonctionne pas encore car ils ne sont pas implémentés dans la bdd. Les styles plateforme devrait être réglés avec le prochain push

**Comment by anisayari** [comment]
Le filtre Plateforme a été résolu avec 85fc357abc16a685808247b6d30a846fecd0da02
