### ISSUE TITLE
Bouton "voir plus" bug

### ISSUE THREAD

**Issue by BenoitObelia** [anisayari/createurstech.fr#38]
Sur mobile, le bouton "voir plus" des créateurs est bug. Quand on clique dessus les informations à voir plus apparaissent au dessus des infos des autres créateurs (voir screen),![Screenshot_20210704-091959_Chrome.jpg](https://user-images.githubusercontent.com/46625877/124376865-45966500-dca9-11eb-8241-d16ac7d02fea.jpg)

**Comment by anisayari** [comment]
Merci ! 
@DimitriTimoz tu peux regarder ça ??

**Comment by anisayari** [comment]
@DimitriTimoz je pense qu'un bouton voir plus avec les formats rectangle. Ça sert plus trop. On va revenir au scroll et laisser la feature voir plus au cas où on en a besoin plus tard.

**Comment by DimitriTimoz** [comment]
Je ne corrige donc pas le bug ? De plus on a une maquette à implémenter.

**Comment by anisayari** [comment]
> Je ne corrige donc pas le bug ? De plus on a une maquette à implémenter.

Non pas la peine. Tu peux faire une PR pour mettre un scroll plutôt sur la description stp ? Comme sur la maquette. Si tu as du temps.

**Comment by anisayari** [comment]
J'ai fermé car on n'affiche plus cette fonctionnalité
