### ISSUE TITLE
Fix card

### ISSUE THREAD

**Issue by anisayari** [anisayari/createurstech.fr#42]
![image](https://user-images.githubusercontent.com/10380894/124390191-b90c9680-dcea-11eb-9bad-a71dcc2dc265.png)

Top @DimitriTimoz . Il y a quelques petit bug. Twitter ne s'affiche pas chez tout le monde.

Et tu peux utiliser les datas "_abbreviations" pour les chiffres ?

Et aussi tu peux sur mobile mettre deux column ? 
Il faut augmenter le height et diminuer le width. Ou faire des taules différentes pour mobile.

Ca serait bien d'avoir une grid de 4 sur desktop et 2 sur mobile.

**Comment by DimitriTimoz** [comment]
Pas de problème, twitter ne s'affiche pas chez certain car il n'y a pas de données pour le nombre de followers

**Comment by DimitriTimoz** [comment]
@anisayari est ce possible de désactiver le css de Jekyll  ? Car il bloque pas mal de chose notamment la largeur du contenu.

**Comment by DimitriTimoz** [comment]
columns dans ce commit:  ba832eed10d6f6964df4ba054a77a85d8b648f72

**Comment by DimitriTimoz** [comment]
#43 corrige tous les problèmes sauf twitter

**Comment by DimitriTimoz** [comment]
> @anisayari est ce possible de désactiver le css de Jekyll ? Car il bloque pas mal de chose notamment la largeur du contenu.

plus vraiment nécessaire mais ça peut simplifier la tâche
