### ISSUE TITLE
Card youtube_subscriber_count_abbreviation text color issue

### ISSUE THREAD

**Issue by jqueguiner** [anisayari/createurstech.fr#51]
![image](https://user-images.githubusercontent.com/690878/124441322-d9d0fc80-dd7b-11eb-8da7-5e3c1c65aeb6.png)

**Comment by DimitriTimoz** [comment]
Pourquoi y a t il 2 fois le nombre d abonnés YouTube sur la carte ?

**Comment by anisayari** [comment]
Fixed with #52

**Comment by anisayari** [comment]
> Pourquoi y a t il 2 fois le nombre d abonnés YouTube sur la carte ?

Ah oui bonne question... Je vais fix ca. Merci

**Comment by jqueguiner** [comment]
can we close this issue ?

**Comment by anisayari** [comment]
Je ferme car on n'affiche plus cette feature
