### ISSUE TITLE
Nettoyer le css

### ISSUE THREAD

**Issue by anisayari** [anisayari/createurstech.fr#54]
J'ai ajouté le css du thème dans _sass et j'ai déplacé notre style dans custom-styles.scss. Il faut nettoyer tout ces fichiers css et gardé uniquement ce qu'on a besoin. 

Pour info le style est importé dans assets/styles.css 
Plus d'info ici : https://jekyllrb.com/docs/assets/ 

La Pull Request correspondante est #53

**Comment by anisayari** [comment]
@DimitriTimoz tu penses que tu pourrais t'occuper de ca ? Vu que c'est toi qui a remonté le problème. Ca peut être d'unifier tout ca.

**Comment by DimitriTimoz** [comment]
> @DimitriTimoz tu penses que tu pourrais t'occuper de ca ? Vu que c'est toi qui a remonté le problème. Ca peut être d'unifier tout ca.
Pas de problème, je regarde ça.

**Comment by DimitriTimoz** [comment]
#55 nettoie le css et ajoute le header & footer

**Comment by anisayari** [comment]
Fixed with #55
