### ISSUE TITLE
Probleme avec une personne qui ne possède pas de compte Youtube 

### ISSUE THREAD

**Issue by zechaos031** [anisayari/createurstech.fr#85]
Je me permet d'ouvrir cette issue car il y a un petit problème sur un créateur

(cette issue fait référence a https://github.com/anisayari/createurstech.fr/pull/82 )

Sur cette image
![image](https://user-images.githubusercontent.com/36123003/124909753-1f473100-dfeb-11eb-8532-5b245a60c7ab.png)

on peu voir qu'aucune chaine youtube est lié or dans le creators.yml qui est généré automatiquement il a était mis avec une chaine youtube (la première de la liste du creator-short.json)

le creators.yml
![image](https://user-images.githubusercontent.com/36123003/124935093-9c7f9f80-e005-11eb-8df9-74c628709c96.png)

le creator-short.json
![image](https://user-images.githubusercontent.com/36123003/124935204-bae59b00-e005-11eb-8cc6-1fae334a730f.png)

Je pense qu'il doit avoir une petite erreur dans le code en backend pour la generation de ce fichier la

**Comment by anisayari** [comment]
Ca a été fixé avec le dernier push merci.
